// uniapp/components/DishCard.vue
<template>
	<view class="dish-card" @tap="handleTap">
		<view class="dish-image">
			<text class="dish-emoji">{{ dish.emoji || '🍽️' }}</text>
			<view class="match-score">
				<text class="score-text">{{ Math.round(dish.matchScore || 0) }}%</text>
			</view>
		</view>
		
		<view class="dish-content">
			<text class="dish-name">{{ dish.name }}</text>
			<text class="dish-description">{{ dish.description }}</text>
			
			<view class="dish-meta">
				<view class="meta-item">
					<text class="meta-icon">⏱️</text>
					<text class="meta-text">{{ dish.cookingTime }}</text>
				</view>
				<view class="meta-item">
					<text class="meta-icon">👨‍🍳</text>
					<text class="meta-text">{{ getDifficultyText(dish.difficulty) }}</text>
				</view>
			</view>
			
			<view class="dish-tags">
				<text 
					v-for="tag in dish.tags.slice(0, 2)" 
					:key="tag"
					class="tag"
				>
					{{ tag }}
				</text>
			</view>
		</view>
	</view>
</template>

<script>
	export default {
		name: 'DishCard',
		props: {
			dish: {
				type: Object,
				required: true
			}
		},
		methods: {
			handleTap() {
				this.$emit('tap', this.dish)
			},
			
			getDifficultyText(difficulty) {
				const difficultyMap = {
					'简单': '简单',
					'中等': '中等', 
					'困难': '困难',
					'1': '简单',
					'2': '中等',
					'3': '困难'
				}
				return difficultyMap[difficulty] || difficulty
			}
		}
	}
</script>

<style lang="scss" scoped>
	.dish-card {
		background: white;
		border-radius: 16px;
		overflow: hidden;
		box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
		transition: all 0.3s ease;
		position: relative;
	}
	
	.dish-card:active {
		transform: scale(0.98);
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
	}
	
	.dish-image {
		height: 120px;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		position: relative;
	}
	
	.dish-emoji {
		font-size: 48px;
	}
	
	.match-score {
		position: absolute;
		top: 8px;
		right: 8px;
		background: rgba(255, 255, 255, 0.9);
		border-radius: 12px;
		padding: 4px 8px;
	}
	
	.score-text {
		font-size: 12px;
		font-weight: 600;
		color: #667eea;
	}
	
	.dish-content {
		padding: 16px;
	}
	
	.dish-name {
		font-size: 16px;
		font-weight: 600;
		color: #1f2937;
		margin-bottom: 4px;
		display: block;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	
	.dish-description {
		font-size: 12px;
		color: #6b7280;
		line-height: 1.4;
		margin-bottom: 12px;
		display: -webkit-box;
		-webkit-line-clamp: 2;
		-webkit-box-orient: vertical;
		overflow: hidden;
	}
	
	.dish-meta {
		display: flex;
		gap: 12px;
		margin-bottom: 12px;
	}
	
	.meta-item {
		display: flex;
		align-items: center;
		gap: 4px;
	}
	
	.meta-icon {
		font-size: 12px;
	}
	
	.meta-text {
		font-size: 12px;
		color: #6b7280;
	}
	
	.dish-tags {
		display: flex;
		gap: 6px;
		flex-wrap: wrap;
	}
	
	.tag {
		padding: 2px 8px;
		background: #f3f4f6;
		color: #6b7280;
		border-radius: 12px;
		font-size: 10px;
		font-weight: 500;
	}
</style>

// client/components/DishCard.tsx
import * as React from 'react';
import { Card, CardContent } from './ui/card';
import { Badge } from './ui/badge';
import { Dish } from './DishRecommendation';

interface DishCardProps {
  dish: Dish & { matchScore?: number };
  onClick?: () => void;
  index: number;
}

const cardGradients = [
  'from-blue-500/10 to-purple-500/10',
  'from-emerald-500/10 to-cyan-500/10',
  'from-orange-500/10 to-red-500/10',
  'from-pink-500/10 to-rose-500/10',
  'from-indigo-500/10 to-blue-500/10',
  'from-lime-500/10 to-green-500/10',
];

const borderGradients = [
  'from-blue-500 to-purple-500',
  'from-emerald-500 to-cyan-500',
  'from-orange-500 to-red-500',
  'from-pink-500 to-rose-500',
  'from-indigo-500 to-blue-500',
  'from-lime-500 to-green-500',
];

export const DishCard = React.forwardRef<HTMLDivElement, DishCardProps>(
  ({ dish, onClick, index }, ref) => {
    const gradientIndex = index % cardGradients.length;
    
    const handleClick = () => {
      if (onClick) {
        onClick();
      }
    };
    
    return (
      <Card 
        ref={ref}
        className={`
          cursor-pointer group relative overflow-hidden
          hover:shadow-2xl hover:shadow-current/20 
          transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]
          bg-gradient-to-br ${cardGradients[gradientIndex]}
          border-2 border-transparent bg-clip-padding
        `}
        onClick={handleClick}
      >
      {/* 渐变边框效果 */}
      <div className={`absolute inset-0 bg-gradient-to-r ${borderGradients[gradientIndex]} opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-lg`} 
           style={{ padding: '2px' }}>
        <div className="bg-card rounded-md h-full w-full"></div>
      </div>
      
      <CardContent className="relative p-4 z-10">
        <div className="space-y-3">
          {/* 匹配度指示器 */}
          {dish.matchScore !== undefined && (
            <div className="flex justify-between items-center">
              <div className={`px-2 py-1 rounded-full text-xs bg-gradient-to-r ${borderGradients[gradientIndex]} text-white`}>
                匹配度 {Math.round(dish.matchScore)}%
              </div>
              <div className="animate-pulse">⭐</div>
            </div>
          )}
          
          {/* 菜品名称和描述 */}
          <div>
            <h3 className="line-clamp-1 bg-gradient-to-r from-gray-800 to-gray-600 bg-clip-text text-transparent group-hover:from-purple-600 group-hover:to-blue-600 transition-all duration-300">
              {dish.name}
            </h3>
            <p className="text-muted-foreground text-sm line-clamp-2 mt-1">
              {dish.description}
            </p>
          </div>
          
          {/* 标签 */}
          <div className="flex flex-wrap gap-1">
            {dish.tags.slice(0, 3).map((tag, tagIndex) => (
              <Badge 
                key={tag} 
                variant="secondary" 
                className={`
                  text-xs transition-all duration-300 hover:scale-110
                  bg-gradient-to-r ${borderGradients[(gradientIndex + tagIndex) % borderGradients.length]} 
                  text-white border-0
                `}
              >
                {tag}
              </Badge>
            ))}
            {dish.tags.length > 3 && (
              <Badge variant="outline" className="text-xs border-gray-300">
                +{dish.tags.length - 3}
              </Badge>
            )}
          </div>
          
          {/* 时间和难度 */}
          <div className="flex justify-between items-center text-sm">
            <span className="flex items-center gap-1 text-emerald-600">
              <span className="animate-pulse">⏱️</span>
              <span>{dish.cookingTime}</span>
            </span>
            <span className="flex items-center gap-1 text-orange-600">
              <span className="animate-pulse">🔥</span>
              <span>{dish.difficulty}</span>
            </span>
          </div>
        </div>
      </CardContent>
      
      {/* 悬浮效果装饰 */}
      <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
        <div className="w-2 h-2 bg-gradient-to-r from-pink-500 to-violet-500 rounded-full animate-ping"></div>
      </div>
    </Card>
    );
  }
);

DishCard.displayName = "DishCard";
